
export const SET_BLOG_PAGE_TARGETED = 'SET_BLOG_PAGE_TARGETED';
export const CLEAR_BLOG_PAGE_TARGETED = 'CLEAR_BLOG_PAGE_TARGETED';

export const SET_BLOG_PAGE_TOTAL = 'SET_BLOG_PAGE_TOTAL';
export const SET_POSTS_FETCHED = 'SET_POST_FETCHED';
